### ISSUE TITLE
Automatically report accuracy

### ISSUE THREAD

**Issue by mubaris** [mubaris/urban-robot#2]
Make a small function to report accuracy of algorithm to the file `accuracy.txt`

**Comment by manparvesh** [comment]
Hi @mubaris,
I'd like to contribute to this issue. Can you please assign this to me?

**Comment by mubaris** [comment]
@manparvesh I have sent to you a collaborator request. Accept it, then I will assign it to you.

**Comment by manparvesh** [comment]
@mubaris I have accepted the invitation.

**Comment by shreyansh26** [comment]
Hi @mubaris , could you please assign me this issue?

**Comment by shreyansh26** [comment]
I have sent a pull request. Please review it.
